### ISSUE TITLE
encoding drills 2

### ISSUE THREAD

**Issue by Strieker** [lmu-cmsi284-spring2019/assignments#8]
@tedmist1 and @dondi; my bad, I thought I submitted this issue already, but its not appearing in my issues queue, so Im creating a new one. Thanks so much!

**Comment by dondi** [comment]
Hello —I’ll keep this issue open in case closing it makes my response harder to see (I responded to the other one but closed it right away, but that might have been missed).

@Strieker The issue needs to come from the repository that you get when you accept/setup the assignment so that the script sends the exercises to the right place....

**Comment by dondi** [comment]
She’s off and encoding 🙂
